###server
server:
  port: 8299
###spring
spring:
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 500MB
  #数据库连接池
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_mca?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 5000
      lettuce:
        pool:
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 16
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
mybatis-plus:
  # 配置slq打印日志
  configuration:

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
